---
- name: This is a hello-world example
  tasks:
    - name: Create a file called 'c:\testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: c:\\testfile.txt